apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 4.0.13
  install:
    createNamespace: true
  interval: 1m
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  values:
    fullnameOverride: ingress-nginx
    controller:
      kind: DaemonSet
      hostNetwork: true
      hostPort:
        enabled: true
      service:
        enabled: true
      publishService:
        enabled: true
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      config:
        use-forwarded-headers: "true"
      extraArgs:
        enable-ssl-passthrough: "true"
      admissionWebhooks:
        enabled: false
      setAsDefaultIngress: "true"
