apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jetstack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: v1.6.1
  install:
    createNamespace: true      
  interval: 5s
  releaseName: jetstack
  targetNamespace: jetstack
  values:
    prometheus:
      enabled: false
      webhook: 
        timeoutSeconds: 4
